### Config file
### set defaults and overrides here
### NOTE: config format may change in the future
metadata:
    title: ''
    lang: 'en'
    publisher: 'SCP Foundation'
    author: 'SCP Foundation'
    creator: 'scp-epub-gen'
input:
  customCSS: ''
  additionalResources: []
  wikidot: true
  #autoLoad: 
output:
  #path: './output'
  #tempDir: './output'
  ### override css folder / anything else included in epub.
  ### using an absolute path is a good idea
  #localResources: './assets'

  ### clear temp folder contents before running
  cleanTempFolder: true

  ### keep temp folder after converting to ebook
  keepTempFiles: false

  images:
    ### set to true to not store images.
    ### Note this isn't very compatible with most ebook readers, but saves a lot of space
    remote: false
    ### compress images. NOTE: if disabled this won't convert webp/other non-compatible types
    compress: true

    ### max width of images
    width: 768
    ### max height of images
    height: 1024
    ### JPEG conversion quality - 70 = higher quality, 30 = smaller size
    quality: 30
    ### convert SVG to png. Recommended
    convertSVG: true
    ### set to true to force everything to JPG instead of PNG if bigger than X bytes
    ### default 102400 = 100kb
    jpegIfSizeLargerThan: 102400
    ### sharp library advanced options
    resizeOptions:
      fit: 'inside'
      withoutEnlargement: true
  diskConcurrency: 1
bookOptions:
  appendixDepthCutoff: 2
  ### whether to include rating info in book
  showRating: true
  ### Whether to include tags at end of chapters
  showTags: true
  ### whether to include detected audio links
  includeAudioAdaptations: true
  hideSupplemental: true
  tocTitle: 'Table Of Contents'
  prefaceTitle: 'Preface'
discovery:
  ### default # of additional articles to pull
  ### setting this too high could increase epub size
  maxChapters: 100
  ### how far down to follow the rabbit - 2 = main page -> linked articles -> linked articles
  maxDepth: 2
  ### default include these articles 
  include: []
  ### default never include these articles
  exclude: []
  ### Origin to use for external links. Could change to https://scp-wiki.wikidot.com or http://scp-wiki.net or http://www.scpwiki.com
  #defaultOrigin: 'http://www.scpwiki.com'
  defaultOrigin: 'https://scp-wiki.wikidot.com/'

  ### KIWIX support - you can try to get content from a KIWIX mirror (https://dev.library.kiwix.org/#lang=eng&q=scp)
  # if using kiwix archive then put the proxy url (remove trailing scp-wiki.wikidot.com)
  #localArchiveProxy: 'http://127.0.0.1:8080/content/scp-wiki_en_all_2024-09/'

browser:
  ##########################################
  ###         NOTE IMPORTANT!!!!!        ###
  ###         !!!!LOOK AT THIS!!!!!      ###
  ##########################################

  ### If you're running this as a node.js project then you shouldn't need to set this value - the correct version *should*
  ### get downloaded correctly
  ### Set this path to the path of a compatible browser for puppeteer to automate
  ### If **MAY** work with your built in browser, but it's intended to work with the specific version this tool
  ### was built against (v131 at time of writing)
  ### See https://pptr.dev/guides/configuration for more info
  ### If for some reason you need to manually download check out https://www.chromium.org/getting-involved/download-chromium/
  ### Set to system version of chrome - MAY NOT WORK
  #executablePath: C:\Program Files\Google\Chrome\Application\chrome.exe
  ### Set to relative path
  #executablePath: chrome-win64/chrome.exe


  ### headless: false === open up the automated browser window while it works
  headless: true
  ### print out debug info as it works
  debug: false
  ### size of browser window. doesn't really change page width, just window size
  width: 768
  ### change browser height
  height: 1024
  timeout: 600000
  ### User agent for created browser to report
  ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
### Cover settings
### NOTE: this is for all books made. You can set the cover for individual books
### by using the book markdown format
cover:
  ### Local path to image file to use as cover
  path: ''
  ### Remote URL to image to use as cover
  url: ''
  ### width of cover image
  width: 1600
  ### height of cover image
  height: 2560
  ### Image JPEG quality of image (if image is jpg)
  quality: 70
  ### the template HTML to use for creating the cover - default should be fine?
  #templateHTML: 'D:/path/to/cover.html'
preProcess:
  ### how many pages to scrape in parallel I found errors when I did more than one at a time on the wikidot side
  concurrency: 1
  closeTabs: true
  skipMetaDepth: 1
  ### whether to re-write any scp-wiki.net links to scp-wiki.wikidot.com
  useWikiDotUrls: true
postProcess:
  ### number of pages to run in parallel when sanitizing xml and adding internal links
  concurrency: 3
static:
  ### Folder to serve static content from. Make absolute path if you want to override it
  root: 'static'
cache:
  ### cache statistics pages, otherwise pull each time
  stats: true
  ### cache pages. Set to false to pull fresh copies each time
  pages: true
  ### path to put cached content
  ### Probably best to set to absolute path
  # path: './cache'
  ### cache files for this long (in milliseconds). Default is 4 months
  # 4 * 30 * 24 * 60 * 60 * 1000
  maxAge: 10368000000
### Whether to try to load page stats from http://scpper.com
enableStats: false
### ebook theme to use when viewing using --view CLI option
view:
  ### options: White Sepia Gray Night
  theme: Night